export type EngineeringPart = {
  id: string
  name: string
  category: string
  material: string
  function: string
  loads: string[]
  designDrivers: string[]
  manufacturing: string[]
  interfaces: string[]
}

export const engineeringParts: Record<string, EngineeringPart> = {
  fuselage: {
    id: 'fuselage',
    name: 'Widebody Fuselage Primary Structure',
    category: 'Structure',
    material: 'Al-Li / CFRP hybrid demonstrator',
    function: 'Carries cabin pressure, global bending and local interface loads between wing, tail, floor, cargo and major attachment regions.',
    loads: ['Cabin pressure', 'Global bending', 'Torsion', 'Ground and maneuver loads'],
    designDrivers: ['Fatigue & damage tolerance', 'Buckling', 'Pressure-cycle durability', 'Maintainability'],
    manufacturing: ['Skin-panel manufacture', 'Frames and stringers', 'Join and fasten', 'Sealant and protective finish'],
    interfaces: ['Wing center section', 'Empennage', 'Floor grid', 'Doors / cut-outs'],
  },
  wing: {
    id: 'wing',
    name: 'Wing Primary Box and Control-Surface Map',
    category: 'Structure + Aerodynamics',
    material: 'Composite skins with metallic and composite substructure',
    function: 'Represents the main lifting surface including the front and rear spars, rib field, stringer-supported skins and major control-surface regions.',
    loads: ['Distributed lift', 'Bending moment', 'Shear force', 'Torsion', 'Fuel / engine inertia'],
    designDrivers: ['Strength', 'Buckling', 'Aeroelastic stiffness', 'Fatigue / impact tolerance'],
    manufacturing: ['Wing-skin build', 'Spar / rib subassembly', 'Wing-box closure', 'Control-surface integration'],
    interfaces: ['Engine pylon', 'Wing center section', 'Fuel system', 'High-lift system'],
  },
  'front-spar': {
    id: 'front-spar',
    name: 'Front Spar',
    category: 'Primary Wing Structure',
    material: 'Composite / metallic spar concept',
    function: 'Forms the forward wall of the wing box and carries significant vertical shear, bending-related axial load and torsional shear flow.',
    loads: ['Vertical shear', 'Axial tension / compression', 'Torsional shear flow', 'Local pylon and systems reactions'],
    designDrivers: ['Web shear buckling', 'Cap strength', 'Load introduction at joints', 'Damage tolerance'],
    manufacturing: ['Spar cap and web build', 'Inspection', 'Drilling and interface prep', 'Wing-box assembly'],
    interfaces: ['Upper skin', 'Lower skin', 'Ribs', 'Leading-edge structure'],
  },
  'rear-spar': {
    id: 'rear-spar',
    name: 'Rear Spar',
    category: 'Primary Wing Structure',
    material: 'Composite / metallic spar concept',
    function: 'Forms the aft wall of the wing box and receives important control-surface, actuator and torsion loads.',
    loads: ['Vertical shear', 'Axial load', 'Torsional shear flow', 'High-lift and spoiler reactions'],
    designDrivers: ['Shear buckling', 'Joint strength', 'Actuator hinge load introduction', 'Fatigue'],
    manufacturing: ['Spar manufacture', 'Fitting installation', 'Precision drilling', 'Wing-box closure'],
    interfaces: ['Skins', 'Ribs', 'Flap support region', 'Spoiler and actuation systems'],
  },
  rib: {
    id: 'rib',
    name: 'Rib Field',
    category: 'Wing Substructure',
    material: 'Aluminium / CFRP rib concept',
    function: 'Maintains the local airfoil geometry, stabilizes the skins and distributes local loads between the front and rear spars.',
    loads: ['Local aerodynamic pressure transfer', 'Fuel pressure and inertia', 'Skin stabilization reactions', 'Bracketed equipment loads'],
    designDrivers: ['Web buckling', 'Cut-out reinforcement', 'Fastener bearing', 'Weight efficiency'],
    manufacturing: ['Machining / forming', 'Cut-out finishing', 'Surface protection', 'Fastened installation'],
    interfaces: ['Front spar', 'Rear spar', 'Upper / lower skins', 'Local systems brackets'],
  },
  stringer: {
    id: 'stringer',
    name: 'Skin Stringer Network',
    category: 'Skin Stiffening',
    material: 'CFRP stiffener / metallic concept',
    function: 'Stiffens the wing skin against buckling and shares spanwise axial load created by wing bending.',
    loads: ['Spanwise axial tension / compression', 'Local bending', 'Skin-stringer shear transfer'],
    designDrivers: ['Compression buckling', 'Bond / fastener integrity', 'Run-out design', 'Impact tolerance'],
    manufacturing: ['Layup or extrusion', 'Trim and inspect', 'Prepare for fastening / bonding', 'Integrate with skin'],
    interfaces: ['Upper / lower skins', 'Ribs', 'Spar caps', 'Run-out terminations'],
  },
  'side-of-body-rib': {
    id: 'side-of-body-rib',
    name: 'Side-of-Body Rib',
    category: 'Root Load Introduction',
    material: 'Reinforced metallic / composite rib concept',
    function: 'Provides a heavy root-rib path for transferring wing-box load into the wing center section and adjacent fuselage structure.',
    loads: ['Wing-root shear', 'Bending load introduction', 'Landing / ground reactions', 'Local fitting loads'],
    designDrivers: ['Joint stiffness', 'Fail-safe load paths', 'Bearing / bypass strength', 'Inspection access'],
    manufacturing: ['Heavy rib manufacture', 'Machined fittings', 'Root assembly', 'Interface drilling'],
    interfaces: ['Wing center section', 'Front spar', 'Rear spar', 'Fuselage side structure'],
  },
  'tank-end-rib': {
    id: 'tank-end-rib',
    name: 'Tank End Rib',
    category: 'Wing Tank Boundary',
    material: 'Sealed rib structure',
    function: 'Defines the fuel-tank boundary region while also transmitting local shear and stabilizing the wing box.',
    loads: ['Fuel pressure', 'Local shear', 'Skin stabilization', 'Seal boundary reactions'],
    designDrivers: ['Seal integrity', 'Buckling', 'Access provisions', 'Maintainability'],
    manufacturing: ['Rib build', 'Sealing features', 'Fastener and sealant application', 'Leak check'],
    interfaces: ['Fuel tank bay', 'Front spar', 'Rear spar', 'Skins and seal systems'],
  },
  'wing-center-section': {
    id: 'wing-center-section',
    name: 'Wing Center Section',
    category: 'Primary Carry-Through Structure',
    material: 'Heavy-gauge metallic / composite carry-through concept',
    function: 'Acts as the carry-through structure that connects the left and right wings through the fuselage and closes the primary global load path.',
    loads: ['Global bending transfer', 'Torsion carry-through', 'Landing gear vicinity loads', 'Fuel and inertia loads'],
    designDrivers: ['Ultimate strength', 'Damage tolerance', 'Assembly access', 'Load-path continuity'],
    manufacturing: ['Major machining / fabrication', 'Subassembly build', 'Fuselage integration', 'Final join'],
    interfaces: ['Fuselage shell', 'Wing root ribs', 'Landing gear beam', 'Center tank region'],
  },
  'landing-gear-beam': {
    id: 'landing-gear-beam',
    name: 'Landing Gear Beam',
    category: 'Local Major Structure',
    material: 'High-strength metallic beam concept',
    function: 'Supports landing-gear related ground-load introduction in the wing-root / center-section vicinity.',
    loads: ['Ground impact loads', 'Taxi and braking loads', 'Local bending and shear'],
    designDrivers: ['Load introduction strength', 'Local buckling', 'Fatigue', 'Maintainability'],
    manufacturing: ['Machining / forging', 'Bracket integration', 'Drilling and bushing', 'Assembly into root region'],
    interfaces: ['Wing center section', 'Root rib system', 'Landing gear structure'],
  },
  'leading-edge-slat': {
    id: 'leading-edge-slat',
    name: 'Leading-Edge Slat Region',
    category: 'High-Lift System',
    material: 'Lightweight metallic / composite surfaces',
    function: 'Improves low-speed lift characteristics and stall margin by modifying the leading-edge flow field.',
    loads: ['Aerodynamic pressure', 'Actuation loads', 'Track / support reactions'],
    designDrivers: ['Smooth deployment', 'Weight', 'Bird-strike resistance', 'Maintainability'],
    manufacturing: ['Surface manufacture', 'Track and fitting install', 'Assembly', 'Rigging'],
    interfaces: ['Leading-edge wing structure', 'Actuation system', 'Tracks and fairings'],
  },
  spoiler: {
    id: 'spoiler',
    name: 'Spoiler Panel Set',
    category: 'Flight Controls',
    material: 'Composite / metallic panels',
    function: 'Provides roll assist, lift dump and speed-brake functionality through upper-surface spoiler deployment.',
    loads: ['Actuator loads', 'Aerodynamic hinge moments', 'Panel support reactions'],
    designDrivers: ['Hinge stiffness', 'Flutter margin', 'Surface fit', 'Maintenance access'],
    manufacturing: ['Panel build', 'Hinge and actuator fitting', 'Rigging', 'Functional testing'],
    interfaces: ['Rear spar', 'Actuation system', 'Upper wing skin'],
  },
  flap: {
    id: 'flap',
    name: 'Inboard Flap Region',
    category: 'High-Lift System',
    material: 'Composite / metallic lifting surface',
    function: 'Provides major trailing-edge camber increase for takeoff and landing performance.',
    loads: ['Aerodynamic pressure', 'Track and carriage loads', 'Actuation loads'],
    designDrivers: ['Stiffness', 'Weight', 'Rigging tolerance', 'Mechanism reliability'],
    manufacturing: ['Flap box assembly', 'Track integration', 'Final rigging', 'Inspection'],
    interfaces: ['Rear spar', 'Track beams', 'Actuation system'],
  },
  flaperon: {
    id: 'flaperon',
    name: 'Flaperon Region',
    category: 'Flight Controls',
    material: 'Composite / metallic control surface',
    function: 'Acts as a trailing-edge control surface contributing to both lift-device and roll-control behavior.',
    loads: ['Hinge moments', 'Actuation loads', 'Aerodynamic pressure'],
    designDrivers: ['Control effectiveness', 'Hinge-line stiffness', 'Flutter', 'Surface alignment'],
    manufacturing: ['Surface build', 'Hinge installation', 'Actuator connection', 'Rigging'],
    interfaces: ['Rear spar', 'Actuators', 'Flight-control system'],
  },
  aileron: {
    id: 'aileron',
    name: 'Aileron Region',
    category: 'Flight Controls',
    material: 'Composite / metallic control surface',
    function: 'Provides primary lateral control at the outer wing.',
    loads: ['Aerodynamic hinge moments', 'Actuator loads', 'Flutter-related dynamic loads'],
    designDrivers: ['Roll effectiveness', 'Mass balance', 'Flutter margin', 'Maintainability'],
    manufacturing: ['Surface build', 'Hinge and actuator install', 'Rigging', 'Balancing'],
    interfaces: ['Rear spar', 'Actuation system', 'Wing tip trailing-edge region'],
  },
  engine: {
    id: 'engine',
    name: 'Large High-Bypass Turbofan Installation',
    category: 'Propulsion',
    material: 'Multi-material thermal / structural system',
    function: 'Provides thrust while transferring engine mass, thrust, torque and transient loads into the wing through the pylon.',
    loads: ['Thrust', 'Gyroscopic loads', 'Vibration', 'Thermal gradients', 'Maneuver inertia'],
    designDrivers: ['Thermal capability', 'Vibration / HCF', 'Containment', 'Fire-zone separation'],
    manufacturing: ['Machining', 'Casting / forging', 'Coatings', 'Precision assembly'],
    interfaces: ['Pylon mounts', 'Fuel', 'Electrical', 'Bleed / ECS interfaces'],
  },
  tail: {
    id: 'tail',
    name: 'Widebody Empennage',
    category: 'Stability & Control',
    material: 'CFRP primary structure concept',
    function: 'Provides longitudinal and directional stability and transfers control-surface loads into the aft fuselage.',
    loads: ['Tailplane lift', 'Rudder side load', 'Gust loads', 'Control actuator loads'],
    designDrivers: ['Stiffness', 'Control effectiveness', 'Flutter', 'Damage tolerance'],
    manufacturing: ['Composite skins', 'Spars / ribs', 'Bonded + fastened joints', 'Surface finishing'],
    interfaces: ['Aft fuselage', 'Elevator', 'Rudder', 'Actuation systems'],
  },
}

export const layers = ['Overview', 'Aerodynamics', 'Structure', 'Loads', 'Manufacturing', 'Systems'] as const
